//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectXwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public int ChapterId { get; set; }
        public int StoryId { get; set; }
        public int ChapterNumber { get; set; }
        public string ChapterTitle { get; set; }
        public string ChapterContent { get; set; }
        public int ChapterStatus { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public string UserId { get; set; }
        public string Slug { get; set; }
    
        public virtual Story Story { get; set; }
    }
}
