//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectXwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string ReviewTitle { get; set; }
        public string ReviewContent { get; set; }
        public short ReviewStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Slug { get; set; }
    }
}
